name: Auto Merge PRs and Delete Branches

on:
  schedule:
    - cron: '0 12 * * 0'  # Runs every Sunday at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable auto-merge for PRs
        run: |
          prs=$(gh pr list --state open --json number -q '.[].number')
          for pr in $prs; do
            echo "Enabling auto-merge for PR #$pr"
            gh pr merge $pr --auto --merge
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete merged branches
        run: |
          prs=$(gh pr list --base main --state merged --json headRefName -q '.[].headRefName')
          for branch in $prs; do
            echo "Deleting branch: $branch"
            gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/$branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
